name: Kyber512
type: kem
claimed-nist-level: 1
claimed-security: IND-CCA2
length-public-key: 800
length-ciphertext: 768
length-secret-key: 1632
length-shared-secret: 32
nistkat-sha256: bb0481d3325d828817900b709d23917cefbc10026fc857f098979451f67bb0ca
principal-submitters:
  - Peter Schwabe
auxiliary-submitters:
  - Roberto Avanzi
  - Joppe Bos
  - Léo Ducas
  - Eike Kiltz
  - Tancrède Lepoint
  - Vadim Lyubashevsky
  - John M. Schanck
  - Gregor Seiler
  - Damien Stehlé
implementations:
    - name: clean
      version: https://github.com/pq-crystals/kyber/commit/2411ffd7c41d49c2e5a356c4704cb9d35485d234
